[profile.default]
solc_version = "0.8.20"

[profile.default.igra]
enabled = true
el_rpc_url = "https://rpc.igralabs.com:8545"
kaspa_rpc_url = "grpc://95.217.73.85:16110"
kaspa_network = "mainnet"
tx_id_prefix = "97b1"
expected_el_chain_id = 38833
el_receipt_timeout_secs = 10

[profile.default.igra.kaspa_wallet]
private_key = "YOUR_64_CHAR_HEX_PRIVATE_KEY"
