[profile.default]

[profile.default.igra]
enabled = true
el_rpc_url = "https://galleon-testnet.igralabs.com:8545"
kaspa_rpc_url = "grpc://95.217.73.85:16110"
kaspa_network = "testnet-10"
tx_id_prefix = "97b4"
expected_el_chain_id = 38836
el_receipt_timeout_secs = 10

[profile.default.igra.kaspa_wallet]
private_key = "YOUR_64_CHAR_HEX_PRIVATE_KEY"
